name: Run SQL and export CSV

on:
  workflow_dispatch: {}  # ручной запуск

jobs:
  run-query:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # Пинним версии из-за несовместимости sshtunnel с новыми Paramiko
          pip install "psycopg2-binary==2.9.9" "sshtunnel==0.4.0" "paramiko==3.3.1"

      - name: Run query (data.sql → raw_data.csv)
        env:
          # DB
          DB1_HOST: ${{ secrets.DB1_HOST }}
          DB1_NAME: ${{ secrets.DB1_NAME }}
          DB1_PASSWORD: ${{ secrets.DB1_PASSWORD }}
          DB1_PORT: ${{ secrets.DB1_PORT }}
          DB1_USER: ${{ secrets.DB1_USER }}
          DB1_SSLMODE: ${{ secrets.DB1_SSLMODE }} # опционально, например "require"
          # SSH (по необходимости)
          USE_SSH: ${{ secrets.USE_SSH }}         # "true"/"false"
          SSH1_HOST: ${{ secrets.SSH1_HOST }}
          SSH1_PORT: ${{ secrets.SSH1_PORT }}
          SSH1_PRIVATE_KEY: ${{ secrets.SSH1_PRIVATE_KEY }}
          SSH1_USER: ${{ secrets.SSH1_USER }}
          # Файлы
          SQL_FILE: data.sql
          OUTPUT_CSV: raw_data.csv
        run: |
          python run_query.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: raw_data
          path: raw_data.csv
          if-no-files-found: error
